import numpy as np
import tempfile
import os

import genesis as gs

def create_rectangular_mesh(width, depth, nx, ny):
    """Create a rectangular mesh grid vertices and faces for a cloth."""
    # vertices
    x = np.linspace(-width/2, width/2, nx)
    y = np.linspace(-depth/2, depth/2, ny)
    xx, yy = np.meshgrid(x, y)
    zz = np.zeros_like(xx)
    vertices = np.stack([xx, zz, yy], axis=-1).reshape(-1, 3)  # shape (nx*ny, 3)
    # faces (triangles)
    faces = []
    for i in range(ny-1):
        for j in range(nx-1):
            idx = i * nx + j
            # triangle 1
            faces.append([idx, idx+1, idx+nx])
            # triangle 2
            faces.append([idx+1, idx+nx+1, idx+nx])
    faces = np.array(faces)
    return vertices, faces

def save_obj_mesh(vertices, faces, path):
    """Save mesh as Wavefront OBJ file."""
    with open(path, 'w') as f:
        f.write("# Cloth mesh generated by Genesis\n")
        for v in vertices:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        f.write("\n")
        for face in faces:
            f.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")

def main():
    gs.init(backend=gs.gpu)  # use GPU if available

    # Create scene
    scene = gs.Scene(show_viewer=True, viewer_options=gs.options.ViewerOptions(camera_pos=(3, -3, 2), camera_lookat=(0, 0, 0)))

    # Add floor plane
    scene.add_entity(morph=gs.morphs.Plane())

    # Add table top as a rigid box
    table_width = 1.2
    table_depth = 0.8
    table_height = 0.05
    table_pos = (0.0, table_height/2, 0.0)  # center at z=0, y up? In Genesis, default up is z? Actually in many examples y is up. We'll assume y-up.
    # To be safe, set morph position accordingly. We'll use box morph with pos.
    table = scene.add_entity(
        morph=gs.morphs.Box(
            pos=(0.0, table_height/2, 0.0),
            size=(table_width, table_height, table_depth),
        ),
        material=gs.materials.Rigid(rho=1000, friction=0.5),
    )

    # Create cloth mesh
    cloth_width = 1.5
    cloth_depth = 1.1
    nx, ny = 30, 22  # resolution
    verts, faces = create_rectangular_mesh(cloth_width, cloth_depth, nx, ny)
    # Position cloth slightly above table top
    cloth_pos_y = table_height + 0.02  # just above table
    verts[:, 1] += cloth_pos_y  # y is up in our coordinate convention? Let's assume y-up.
    # Actually in Genesis, default is z-up? Looking at API: Plane morph normal is (0,0,1). So up is z.
    # We need to adapt. Let's assume z-up. Reorient.
    # Use z as vertical.
    # We'll regenerate mesh with z as up.
    # Let's redefine create_rectangular_mesh with y as horizontal, z vertical.
    # We'll just manipulate the vertices array: old x->x, old y->z, old z->y? Better to create mesh in xz plane.
    # Let's create properly.

    # Actually simpler: use the function above but swap y and z after creation.
    # Let's regenerate:
    verts, faces = create_rectangular_mesh(cloth_width, cloth_depth, nx, ny)
    # verts: x, y, z where y is initially zero. We want z up. So set z = y (which is 0) and y = something?
    # We'll position cloth with z = table_height+0.02.
    verts[:, 2] += table_height + 0.02
    # Now save to temporary OBJ
    tmp_dir = tempfile.mkdtemp()
    obj_path = os.path.join(tmp_dir, "cloth.obj")
    save_obj_mesh(verts, faces, obj_path)

    # Add cloth entity using mesh morph and PBD cloth material
    cloth_mat = gs.materials.PBD.Cloth(
        rho=4.0,
        static_friction=0.3,
        kinetic_friction=0.3,
        stretch_compliance=1e-6,
        bending_compliance=1e-4,
    )
    cloth = scene.add_entity(
        morph=gs.morphs.Mesh(file=obj_path, scale=1.0, pos=(0,0,0)),
        material=cloth_mat,
    )

    # Add cups and plates as rigid bodies
    # Cup: small cylinder approximated by a box? Use box for simplicity.
    cup_positions = [(0.4, 0.0, 0.3), (-0.3, 0.0, -0.2), (0.5, 0.0, -0.3)]
    for pos in cup_positions:
        scene.add_entity(
            morph=gs.morphs.Box(pos=(pos[0], pos[1], pos[2]+table_height+0.5), size=(0.08, 0.10, 0.08)),
            material=gs.materials.Rigid(rho=500, friction=0.5),
        )

    # Plate: thin box
    plate_positions = [(-0.2, 0.0, 0.4), (0.2, 0.0, -0.4)]
    for pos in plate_positions:
        scene.add_entity(
            morph=gs.morphs.Box(pos=(pos[0], pos[1], pos[2]+table_height+0.3), size=(0.25, 0.02, 0.25)),
            material=gs.materials.Rigid(rho=600, friction=0.4),
        )

    # Build the scene
    scene.build()

    # Simulate
    for i in range(500):
        scene.step()

    # Cleanup temporary mesh file
    os.remove(obj_path)
    os.rmdir(tmp_dir)

if __name__ == "__main__":
    main()